version: "3"

services:
  battleship_auth:
    image: battleship/auth:${TAG:-latest}
    restart: unless-stopped
    links:
      - db
    ports:
      - 3000:3000
    environment:
      DB_NAME: ${DO_DB_NAME}
      DB_HOST: ${DO_DB_HOST}
      DB_PORT: ${DO_DB_PORT}
      DB_USER: ${DO_DB_USER}
      DB_PASSWORD: ${DO_DB_PASSWORD}
      JWT_SECRET: ${BATTLESHIP_JWT_SECRET}
    build:
      context: .
      dockerfile: Dockerfile
